name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

#     - name: Build
#       run: go build -v ./...

    # Needs to be run as root, for mocking SMTP
    - name: Test
      run: |
        sudo mkdir -p /root/go/src/github.com/p0l0
        sudo ln -s $PWD /root/go/src/github.com/p0l0/web-content-change-detector
        sudo cd /root/go/src/github.com/p0l0/web-content-change-detector
        sudo make test
